"""
============================================================
CONFIDENCE ENGINE
============================================================

Purpose
-------
Calculate confidence for extracted packaged-commodity fields.

IMPORTANT:

OCR confidence != field confidence.

Example:

    OCR sees:

        399

    OCR confidence:
        0.97

But the system still needs to determine:

        Is 399 MRP?
        Is 399 a batch number?
        Is 399 part of an address?

Therefore this module combines:

    1. OCR confidence
    2. semantic/field confidence
    3. value-format confidence
    4. spatial relationship
    5. neighboring evidence
    6. consistency
    7. ambiguity penalty

============================================================
"""

import math
import re
from typing import Any, Dict, List, Optional


# ============================================================
# CONFIGURATION
# ============================================================

WEIGHTS = {

    "ocr":
        0.30,

    "semantic":
        0.25,

    "format":
        0.20,

    "spatial":
        0.10,

    "context":
        0.10,

    "consistency":
        0.05,
}


# ============================================================
# CLAMP
# ============================================================

def clamp(
    value: float,
    minimum: float = 0.0,
    maximum: float = 1.0
) -> float:

    return max(
        minimum,
        min(
            maximum,
            float(value)
        )
    )


# ============================================================
# SAFE FLOAT
# ============================================================

def safe_float(
    value: Any,
    default: float = 0.0
) -> float:

    try:

        return float(
            value
        )

    except (
        TypeError,
        ValueError
    ):

        return default


# ============================================================
# NORMALIZED OCR CONFIDENCE
# ============================================================

def ocr_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    Extract OCR confidence from a candidate/detection.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    value = candidate.get(
        "ocr_confidence"
    )

    if value is None:

        value = candidate.get(
            "confidence"
        )

    if value is None:

        detection = candidate.get(
            "detection"
        )

        if isinstance(
            detection,
            dict
        ):

            value = detection.get(
                "confidence",
                0.0
            )

    return clamp(
        safe_float(
            value
        )
    )


# ============================================================
# SEMANTIC CONFIDENCE
# ============================================================

def semantic_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    How strongly the text matches the intended field.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    for key in (
        "semantic_score",
        "field_score",
        "classification_score"
    ):

        if key in candidate:

            return clamp(
                safe_float(
                    candidate[key]
                )
            )

    # Candidate generated by field_classifier.
    return clamp(
        safe_float(
            candidate.get(
                "score",
                0.0
            )
        )
    )


# ============================================================
# FORMAT CONFIDENCE
# ============================================================

def format_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    Confidence based on whether the value looks correct
    for the intended field.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    for key in (
        "format_score",
        "value_format_score"
    ):

        if key in candidate:

            return clamp(
                safe_float(
                    candidate[key]
                )
            )

    return 0.0


# ============================================================
# SPATIAL CONFIDENCE
# ============================================================

def spatial_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    Confidence based on proximity to the field heading.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    for key in (
        "spatial_score",
        "relationship_score"
    ):

        if key in candidate:

            return clamp(
                safe_float(
                    candidate[key]
                )
            )

    return 0.0


# ============================================================
# CONTEXT CONFIDENCE
# ============================================================

def context_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    Confidence from surrounding OCR evidence.

    Example:

        MRP
        ₹399

    gives stronger context than:

        ₹399

    alone.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    if "context_score" in candidate:

        return clamp(
            safe_float(
                candidate[
                    "context_score"
                ]
            )
        )

    neighbors = candidate.get(
        "neighbors"
    )

    if not neighbors:

        return 0.0

    # More useful neighbors increase confidence,
    # but with diminishing returns.
    useful = 0

    for neighbor in neighbors:

        if isinstance(
            neighbor,
            dict
        ):

            useful += 1

    return clamp(
        1.0
        -
        math.exp(
            -useful / 2.0
        )
    )


# ============================================================
# CONSISTENCY
# ============================================================

def consistency_confidence(
    candidate: Dict[str, Any]
) -> float:
    """
    Confidence from multiple OCR passes agreeing on
    the same value.
    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    if "consistency_score" in candidate:

        return clamp(
            safe_float(
                candidate[
                    "consistency_score"
                ]
            )
        )

    occurrences = candidate.get(
        "occurrences"
    )

    if occurrences is None:

        occurrences = candidate.get(
            "support_count",
            1
        )

    occurrences = max(
        1,
        int(
            safe_float(
                occurrences,
                1
            )
        )
    )

    # Saturating score.
    return clamp(
        1.0
        -
        math.exp(
            -occurrences / 2.0
        )
    )


# ============================================================
# AMBIGUITY
# ============================================================

def ambiguity_penalty(
    candidate: Dict[str, Any]
) -> float:
    """
    Penalize cases where multiple fields have nearly identical
    classification scores.

    Example:

        399

    could potentially be:

        MRP
        batch
        address fragment

    """

    if not isinstance(
        candidate,
        dict
    ):

        return 0.0

    alternatives = candidate.get(
        "alternatives"
    )

    if not alternatives:

        return 0.0

    scores = []

    for alternative in alternatives:

        if not isinstance(
            alternative,
            dict
        ):
            continue

        score = safe_float(
            alternative.get(
                "score",
                0.0
            )
        )

        scores.append(
            score
        )

    if len(scores) < 2:

        return 0.0

    scores.sort(
        reverse=True
    )

    gap = (
        scores[0]
        -
        scores[1]
    )

    # Large gap = low ambiguity.
    if gap >= 0.35:
        return 0.0

    if gap >= 0.20:
        return 0.05

    if gap >= 0.10:
        return 0.12

    return 0.20


# ============================================================
# FIELD CONFIDENCE
# ============================================================

def calculate_field_confidence(
    candidate: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Calculate combined field confidence.

    Returns:

        {
            "score": 0.91,
            "percentage": 91.0,
            "level": "HIGH",
            ...
        }
    """

    ocr = ocr_confidence(
        candidate
    )

    semantic = semantic_confidence(
        candidate
    )

    format_score = format_confidence(
        candidate
    )

    spatial = spatial_confidence(
        candidate
    )

    context = context_confidence(
        candidate
    )

    consistency = consistency_confidence(
        candidate
    )

    penalty = ambiguity_penalty(
        candidate
    )

    # --------------------------------------------------------
    # Weighted score.
    # --------------------------------------------------------

    score = (

        ocr
        *
        WEIGHTS["ocr"]

        +

        semantic
        *
        WEIGHTS["semantic"]

        +

        format_score
        *
        WEIGHTS["format"]

        +

        spatial
        *
        WEIGHTS["spatial"]

        +

        context
        *
        WEIGHTS["context"]

        +

        consistency
        *
        WEIGHTS["consistency"]

        -
        penalty
    )

    score = clamp(
        score
    )

    # --------------------------------------------------------
    # Level.
    # --------------------------------------------------------

    if score >= 0.85:

        level = "VERY HIGH"

    elif score >= 0.70:

        level = "HIGH"

    elif score >= 0.50:

        level = "MEDIUM"

    elif score >= 0.30:

        level = "LOW"

    else:

        level = "VERY LOW"

    return {

        "score":
            round(
                score,
                4
            ),

        "percentage":
            round(
                score * 100,
                1
            ),

        "level":
            level,

        "components": {

            "ocr":
                round(
                    ocr,
                    4
                ),

            "semantic":
                round(
                    semantic,
                    4
                ),

            "format":
                round(
                    format_score,
                    4
                ),

            "spatial":
                round(
                    spatial,
                    4
                ),

            "context":
                round(
                    context,
                    4
                ),

            "consistency":
                round(
                    consistency,
                    4
                ),

            "ambiguity_penalty":
                round(
                    penalty,
                    4
                ),
        }
    }


# ============================================================
# CONFIDENCE LEVEL
# ============================================================

def confidence_level(
    score: float
) -> str:

    score = clamp(
        score
    )

    if score >= 0.85:
        return "VERY HIGH"

    if score >= 0.70:
        return "HIGH"

    if score >= 0.50:
        return "MEDIUM"

    if score >= 0.30:
        return "LOW"

    return "VERY LOW"


# ============================================================
# OCR QUALITY
# ============================================================

def calculate_ocr_quality(
    detections: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Calculate overall OCR quality.

    This is different from field confidence.
    """

    if not detections:

        return {

            "score": 0.0,

            "percentage": 0.0,

            "level": "VERY LOW",

            "detection_count": 0,
        }

    confidences = []

    for detection in detections:

        if not isinstance(
            detection,
            dict
        ):
            continue

        confidence = safe_float(
            detection.get(
                "confidence",
                0.0
            )
        )

        confidences.append(
            clamp(
                confidence
            )
        )

    if not confidences:

        return {

            "score": 0.0,

            "percentage": 0.0,

            "level": "VERY LOW",

            "detection_count": 0,
        }

    # --------------------------------------------------------
    # Average.
    # --------------------------------------------------------

    average = sum(
        confidences
    ) / len(
        confidences
    )

    # --------------------------------------------------------
    # Strong detection ratio.
    # --------------------------------------------------------

    strong_ratio = sum(
        1
        for value in confidences
        if value >= 0.70
    ) / len(
        confidences
    )

    # --------------------------------------------------------
    # Weak detection penalty.
    # --------------------------------------------------------

    weak_ratio = sum(
        1
        for value in confidences
        if value < 0.30
    ) / len(
        confidences
    )

    score = (
        average * 0.65
        +
        strong_ratio * 0.35
        -
        weak_ratio * 0.15
    )

    score = clamp(
        score
    )

    return {

        "score":
            round(
                score,
                4
            ),

        "percentage":
            round(
                score * 100,
                1
            ),

        "level":
            confidence_level(
                score
            ),

        "average_ocr_confidence":
            round(
                average,
                4
            ),

        "strong_detection_ratio":
            round(
                strong_ratio,
                4
            ),

        "weak_detection_ratio":
            round(
                weak_ratio,
                4
            ),

        "detection_count":
            len(
                confidences
            ),
    }


# ============================================================
# FIELD CONFIDENCE FROM CLASSIFIER RESULT
# ============================================================

def confidence_from_classifier_candidate(
    candidate: Dict[str, Any],
    detection: Optional[
        Dict[str, Any]
    ] = None
) -> Dict[str, Any]:
    """
    Convert field_classifier output into final confidence.
    """

    data = dict(
        candidate
    )

    if detection:

        data.setdefault(
            "detection",
            detection
        )

        data.setdefault(
            "ocr_confidence",
            detection.get(
                "confidence",
                0.0
            )
        )

    return calculate_field_confidence(
        data
    )


# ============================================================
# CONFIDENCE FOR MULTIPLE CANDIDATES
# ============================================================

def rank_candidates_by_confidence(
    candidates: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Add confidence to candidate list and rank it.
    """

    ranked = []

    for candidate in candidates:

        if not isinstance(
            candidate,
            dict
        ):
            continue

        confidence = (
            calculate_field_confidence(
                candidate
            )
        )

        item = dict(
            candidate
        )

        item[
            "confidence"
        ] = confidence

        item[
            "confidence_score"
        ] = confidence[
            "score"
        ]

        ranked.append(
            item
        )

    ranked.sort(
        key=lambda item:
        item.get(
            "confidence_score",
            0.0
        ),
        reverse=True
    )

    return ranked


# ============================================================
# CONFIDENCE SUMMARY
# ============================================================

def summarize_confidence(
    fields: Dict[str, Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Summarize confidence of structured extracted fields.

    Example:

        {
            "mrp": {
                "confidence_score": 0.92
            }
        }
    """

    if not fields:

        return {

            "overall_score": 0.0,

            "overall_percentage": 0.0,

            "level": "VERY LOW",

            "field_count": 0,

            "high_confidence_fields": 0,

            "low_confidence_fields": 0,
        }

    scores = []

    for field_data in fields.values():

        if not isinstance(
            field_data,
            dict
        ):
            continue

        score = field_data.get(
            "confidence_score"
        )

        if score is None:

            confidence = field_data.get(
                "confidence"
            )

            if isinstance(
                confidence,
                dict
            ):

                score = confidence.get(
                    "score",
                    0.0
                )

        if score is not None:

            scores.append(
                clamp(
                    safe_float(
                        score
                    )
                )
            )

    if not scores:

        return {

            "overall_score": 0.0,

            "overall_percentage": 0.0,

            "level": "VERY LOW",

            "field_count": 0,

            "high_confidence_fields": 0,

            "low_confidence_fields": 0,
        }

    average = sum(
        scores
    ) / len(
        scores
    )

    high = sum(
        1
        for score in scores
        if score >= 0.70
    )

    low = sum(
        1
        for score in scores
        if score < 0.50
    )

    return {

        "overall_score":
            round(
                average,
                4
            ),

        "overall_percentage":
            round(
                average * 100,
                1
            ),

        "level":
            confidence_level(
                average
            ),

        "field_count":
            len(
                scores
            ),

        "high_confidence_fields":
            high,

        "low_confidence_fields":
            low,
    }


# ============================================================
# PUBLIC EXPORT
# ============================================================

__all__ = [

    "calculate_field_confidence",

    "confidence_level",

    "calculate_ocr_quality",

    "confidence_from_classifier_candidate",

    "rank_candidates_by_confidence",

    "summarize_confidence",
]